export const COLORS = {
	headerBG: '#fff',
	pageBG: '#586670',
	chatBG: '#d7dfe7',
	chatHeaderBG: '#becbd9',
	contactsBG: '#fff',
	msgOwn: '#f0cbb3',
	msgOther: '#becbd9',
	msgBase: '#fff',
	msgUsername: 'rgba(0, 0, 0, 0.6)',
	msgTime: 'rgba(0, 0, 0, 0.2)',
	msgSeenTime: 'rgba(0, 0, 0, 0.3)',
	messageInputBorder: '#74b9ef',
	button: '#428bca',
	buttonText: '#fff',
	chatInfoText: '#3a87ae',
	scrollbarTrack: '#becbd9',
	scrollbarThumb: '#9daab9',
	onlineStatus: '#20d63e',
	offlineStatus: '#d6d6d6',
	badge: '#d62020',
	badgeText: '#fff',
	tabText: '#555',
	darkText: '#333',
	lightText: '#999',
	lightBorder: '#ccc',
	lightBG: '#f8f8f8',
}
